<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Adjustments</name>
   <tag></tag>
   <elementGuidId>a40916d8-7c51-45a6-b5d5-b5c3eb453cdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b5-Menu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b5-Menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1517967b-7a0d-48ab-84e7-32bc02fc1173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header__item</value>
      <webElementGuid>af7d024b-cf15-4408-8f10-2504465ff730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b5-Menu</value>
      <webElementGuid>a548619f-8261-4005-8f0b-e376bef35978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Adjustments</value>
      <webElementGuid>7430b2ca-fea2-4a7c-82ef-fa78e891f30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b5-Menu&quot;)</value>
      <webElementGuid>bd83099b-4093-4336-aa96-66aa3ea4f585</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b5-Menu']</value>
      <webElementGuid>afc30bd7-f82a-4825-9626-e294ff4e373b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b5-SubMenuHeader']/div</value>
      <webElementGuid>5684b43e-6328-441d-b4d8-de7e4b4024bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Details'])[1]/following::div[4]</value>
      <webElementGuid>d741cec2-1ab7-4cb0-808d-e8a59f3c2e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual Entries'])[1]/following::div[4]</value>
      <webElementGuid>4d779372-ead2-425f-aee0-d5a60a8f0a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adjustment Entries'])[1]/preceding::div[2]</value>
      <webElementGuid>93aed907-3d75-4e79-a4be-0f804e683ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>053a80ed-35f7-4668-a813-f98a688b3011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b5-Menu' and (text() = ' Adjustments' or . = ' Adjustments')]</value>
      <webElementGuid>1b6a46e7-d961-47c8-8988-11f31d2fa334</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
