<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Adjustment Enrties_l4-110_0-Checkbox9</name>
   <tag></tag>
   <elementGuidId>e1190084-7eb2-498c-875b-da2c8b95b6bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='l4-110_0-Checkbox9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#l4-110_0-Checkbox9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00a05cf8-4815-48c3-86b4-044c95f0f477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0fa86789-67c9-46ae-aab0-112946222928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f5c64877-43a9-459a-bfc6-275b7c4019d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l4-110_0-Checkbox9</value>
      <webElementGuid>351e6be4-4820-489e-affc-ab72eb70b991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l4-110_0-Checkbox9&quot;)</value>
      <webElementGuid>a8417be7-e621-4346-89f4-df502df1512b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='l4-110_0-Checkbox9']</value>
      <webElementGuid>07c7623d-e3dc-4338-9bc2-56be181141c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AdjustmentslAccounts2_3']/div[3]/div/div/span/input</value>
      <webElementGuid>6a46dd07-bb5a-4a89-9254-d2da270a0bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/span/input</value>
      <webElementGuid>702bdc53-1d25-4eeb-ba80-d56db8278101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'l4-110_0-Checkbox9']</value>
      <webElementGuid>bae0e41a-6637-4612-9e9b-be1db04eae8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
