<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select PositionGeneral Accoun_7b558e</name>
   <tag></tag>
   <elementGuidId>cd852d1c-8002-4554-bdf0-c03374b662ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dropdown2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Dropdown2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>67409f35-50db-4238-92f1-0890f50fa9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>1579378a-30d1-43e8-99fa-9a12ecd6c49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e2f7769e-eb28-46c5-9359-67dd7c616c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown2</value>
      <webElementGuid>8dea984e-1e1e-48e7-8213-39ed8541aa59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select PositionGeneral AccountantExecutive DirectorAdministratorCashierSupervisorFinance ManagerSr. Finance OfficerFinance BookkeeperAuditorExternal AuditorFinance AssistantFinance OfficerSuper Admin</value>
      <webElementGuid>7e9f7191-95cf-467e-8475-2972757e8da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown2&quot;)</value>
      <webElementGuid>7786060d-bfeb-4fc2-966e-b1eaf4709ac0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dropdown2']</value>
      <webElementGuid>934e285c-cf86-42a0-9bde-87d8910bb739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dropdown2-container']/select</value>
      <webElementGuid>96e87473-b8f7-4bc5-a914-4efe434c8c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Position:'])[1]/following::select[1]</value>
      <webElementGuid>e3f3e843-699f-4b44-843d-e7ce96eb090a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/following::select[1]</value>
      <webElementGuid>c1389985-45fb-47e8-8bc0-7abfd26844b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grant Access Role'])[1]/preceding::select[1]</value>
      <webElementGuid>f5bb32a6-4ebc-4bf0-91a6-b6990e29bb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[1]</value>
      <webElementGuid>89025d0a-256d-4d27-9bb2-6fd4d0ff9120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a04b8b12-93fb-4173-a898-a3b4f676788b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dropdown2' and (text() = 'Please Select PositionGeneral AccountantExecutive DirectorAdministratorCashierSupervisorFinance ManagerSr. Finance OfficerFinance BookkeeperAuditorExternal AuditorFinance AssistantFinance OfficerSuper Admin' or . = 'Please Select PositionGeneral AccountantExecutive DirectorAdministratorCashierSupervisorFinance ManagerSr. Finance OfficerFinance BookkeeperAuditorExternal AuditorFinance AssistantFinance OfficerSuper Admin')]</value>
      <webElementGuid>0ec7c633-3ebc-4a0e-874a-79209f844d82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
