<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manage Roles</name>
   <tag></tag>
   <elementGuidId>b908757f-fa1d-4dac-8417-51b152a39b18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-ManageRoles2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='b2-ManageRoles2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2bb6a0eb-a2a3-4013-aff8-787b3a28cc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ThemeGrid_MarginGutter</value>
      <webElementGuid>ebbba33b-adee-4039-bef2-ff378fed37c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/AccountingSystem/ManageRoles</value>
      <webElementGuid>91591255-4803-4dd6-915a-ee15e4f921a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-ManageRoles2</value>
      <webElementGuid>6aeb855d-555e-4a9d-a3fd-1d6707e3df1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>f17357b3-4fc5-42f4-b173-e90c7e1a002b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>081303f5-c275-4c8f-b4d0-730ebf05ccfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Roles</value>
      <webElementGuid>85a75ed2-e0fc-4e93-ab95-3e6c94d73915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-ManageRoles2&quot;)</value>
      <webElementGuid>af1c5ad0-c516-4e6f-9adf-12245a8a4184</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='b2-ManageRoles2']</value>
      <webElementGuid>d14d63df-ab50-4d59-97db-c4229b4cee7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b12-Items']/a[2]</value>
      <webElementGuid>be06d5f0-e966-4415-b705-4ec6eb878dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Manage Roles')]</value>
      <webElementGuid>f46fa89b-b67b-4617-8e51-a5de80af91b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Management'])[1]/following::a[1]</value>
      <webElementGuid>02a9eadb-56e1-4917-b625-0bc68dcee46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Utilities'])[2]/following::a[2]</value>
      <webElementGuid>022f335c-9e9c-41ed-8373-473c7bc5719d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Parameter'])[1]/preceding::a[1]</value>
      <webElementGuid>9ccd77ce-4f70-4b7b-b648-eb730c1dfbec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Area'])[1]/preceding::a[2]</value>
      <webElementGuid>c9163e1f-737b-4202-b1c7-ffec8df612f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manage Roles']/parent::*</value>
      <webElementGuid>48d3018e-8be8-4364-8463-28b34ea9efa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/AccountingSystem/ManageRoles')]</value>
      <webElementGuid>170e6982-2c89-49e1-8d1a-1683e3d76dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div[2]/a[2]</value>
      <webElementGuid>057ed862-3262-4b6d-8c88-6a023247183d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/AccountingSystem/ManageRoles' and @id = 'b2-ManageRoles2' and (text() = 'Manage Roles' or . = 'Manage Roles')]</value>
      <webElementGuid>de11d694-d8ef-4554-b836-34cc8ed7c9e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
