<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account Number_Input_AccountNumber</name>
   <tag></tag>
   <elementGuidId>40c8896e-11d0-47cd-9152-25fafb25e8e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_AccountNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Input_AccountNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8096abcd-ea89-466f-adad-90092b993d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent not-valid</value>
      <webElementGuid>c8cc5fda-4473-4c64-b403-301a20188db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d27a108b-f0e8-49af-b78c-f28a89b9a044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>4662db5c-1470-4d8d-8406-b222982314ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>9223372036854775807</value>
      <webElementGuid>2b3e4d57-fdb2-41cb-b87b-7e168212604d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_AccountNumber</value>
      <webElementGuid>44a4b5d8-c765-4961-976d-6fecd1777409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_AccountNumber&quot;)</value>
      <webElementGuid>8556c0fa-4fd5-4a84-94d1-6773a47a8437</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_AccountNumber']</value>
      <webElementGuid>42f9031a-6668-4b47-b7e5-31152fc6a455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b6-Column3']/span/input</value>
      <webElementGuid>91568a68-d07a-47ce-95da-b0ba858b8fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/input</value>
      <webElementGuid>e60208a1-3b46-42a6-aa1a-6fc2f58f74d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'Input_AccountNumber']</value>
      <webElementGuid>d7eb1a96-f54d-478a-8b87-f763e76f67b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
