<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Accrued Income Tax Payable 2-21-214-1_ce51c1</name>
   <tag></tag>
   <elementGuidId>6ce62b9d-4f45-4232-b049-0f8c76bbca3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='l5_0-87_0-Input_Debit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#l5_0-87_0-Input_Debit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0bcfd9d-031f-4fd2-abf4-db83d898d441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent not-valid</value>
      <webElementGuid>fa6ddaa8-33cb-4b51-a6e4-d8fa0c6ca0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>aa3f7bd5-aa22-4281-b33c-301e644f0dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]+.[0-9]*</value>
      <webElementGuid>c23c6c90-a26a-472c-94d7-3c3d134db8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>614a5a9c-2ec3-4f4f-a229-15e460b28b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l5_0-87_0-Input_Debit</value>
      <webElementGuid>3c7ad403-fc3b-4429-abe1-e2be465dc6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l5_0-87_0-Input_Debit&quot;)</value>
      <webElementGuid>24417b34-d179-4001-a889-51e2fbf94f71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='l5_0-87_0-Input_Debit']</value>
      <webElementGuid>26232e04-4061-4eba-9e79-e4b7641558d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TransactionDetail']/table/tbody/tr/td[2]/div/span/input</value>
      <webElementGuid>e7875a75-7bd3-45d1-88f8-c21d971dbbcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/span/input</value>
      <webElementGuid>de1fac0c-7bbe-47a2-945f-4f90bfe2bbc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'l5_0-87_0-Input_Debit']</value>
      <webElementGuid>73681309-5088-4315-8154-04ac59f3e8f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
