<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cash in Bank - BPI - Demand Deposit (_afb5f9</name>
   <tag></tag>
   <elementGuidId>264ccbb6-1906-4fe9-8e59-5d39c2fbb585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='l5_0-87_1-Input_Credit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#l5_0-87_1-Input_Credit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15d43368-2eea-4f95-ad7c-edc0d3d077e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>30552941-930c-4d88-b973-a36d9ec74a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ce5e7253-29a0-4a7a-8ec1-5002ab04714f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]+.[0-9]*</value>
      <webElementGuid>68b455a0-11dc-436d-9888-ad7eec7f1239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>82e666ba-70b1-4ecf-95e2-c4a561a7bd04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l5_0-87_1-Input_Credit</value>
      <webElementGuid>3b60351e-3f2d-4e85-a422-b8af60463c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l5_0-87_1-Input_Credit&quot;)</value>
      <webElementGuid>b94843c1-76bf-4239-9f8d-c29918cfbdee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='l5_0-87_1-Input_Credit']</value>
      <webElementGuid>32655249-a012-4d7e-a262-7eecc258e420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TransactionDetail']/table/tbody/tr[2]/td[3]/div/span/input</value>
      <webElementGuid>f0f44702-dfd0-4626-bacb-6bc09328b1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/span/input</value>
      <webElementGuid>6c46d722-4681-4f95-9a61-c19adff21463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'l5_0-87_1-Input_Credit']</value>
      <webElementGuid>140118e4-0608-4437-b95a-c4e0c81f5777</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
