<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No results found_vscomp-search-input</name>
   <tag></tag>
   <elementGuidId>09b35614-3131-4997-b04e-8ec7a8948b97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vscomp-dropbox-container-5306 > div.vscomp-dropbox > div.vscomp-search-wrapper > div.vscomp-search-container > input.vscomp-search-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49a51555-b0d3-4820-b5f0-0867dcb5ad87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa0f3568-345e-4cf1-b6f7-0696b7502bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vscomp-search-input</value>
      <webElementGuid>62baa279-cf9c-46e1-8818-fd17a57e6412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>dbf6f2a2-d201-4434-8f13-fac94f1d03a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vscomp-dropbox-container-5306&quot;)/div[@class=&quot;vscomp-dropbox&quot;]/div[@class=&quot;vscomp-search-wrapper&quot;]/div[@class=&quot;vscomp-search-container&quot;]/input[@class=&quot;vscomp-search-input&quot;]</value>
      <webElementGuid>4876b975-4550-46ea-9e9f-6bdce4ceac4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>8715bd11-5374-4e7d-83dc-a0a879e81bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vscomp-dropbox-container-5306']/div/div/div/input</value>
      <webElementGuid>cf31215e-75d7-4a6b-8d99-d6f99e7fe7c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/input</value>
      <webElementGuid>54e11d66-9c52-4b41-baea-acd832029494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search']</value>
      <webElementGuid>580c1d51-9aae-4eef-987e-a504505c4a3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
