<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cash in Bank - BPI - Demand Deposit (_d2ea01</name>
   <tag></tag>
   <elementGuidId>291fe7a3-74a2-45ac-9921-55983b09b317</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='l5_0-87_1-Input_Debit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#l5_0-87_1-Input_Debit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d00f6e11-a11f-4e7d-a37b-43d9af506fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>39c64a36-8a6c-4cc7-8469-c1349f10e366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4a8ddfaa-da8f-4031-b354-b928d71414f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]+.[0-9]*</value>
      <webElementGuid>b00d2ced-e609-4f2a-a40b-b57c523783a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>f1f4f54c-868e-4b94-a67e-6d19bf7bb6d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l5_0-87_1-Input_Debit</value>
      <webElementGuid>e8f279c0-7b77-4c52-aa5c-f89d1723fcff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l5_0-87_1-Input_Debit&quot;)</value>
      <webElementGuid>a8fa1c48-1008-4f71-b4d6-f4e42878c7e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='l5_0-87_1-Input_Debit']</value>
      <webElementGuid>267d9451-b5e5-4661-a1fe-71702ff51638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TransactionDetail']/table/tbody/tr[2]/td[2]/div/span/input</value>
      <webElementGuid>5e08a46c-252e-4cbf-920c-4c9025c25ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/span/input</value>
      <webElementGuid>be1a0187-4e1a-40cc-bf80-af5e203cfea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'l5_0-87_1-Input_Debit']</value>
      <webElementGuid>f24c7463-4964-482b-a108-69585bf69dc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
