<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_This field is required_l5_0-87_0-Inpu_e552a4</name>
   <tag></tag>
   <elementGuidId>711e5e8f-5f0d-4c5a-a34f-18adef0b9f4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='l5_0-87_0-Input_Credit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#l5_0-87_0-Input_Credit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>055c9c32-6609-4a9a-99f7-f71d32ef85f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent not-valid</value>
      <webElementGuid>3d8b8af0-1c57-4073-ab26-1d7b9e20a665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7d0caa3f-fe38-402f-b7f8-efa57f67e3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]+.[0-9]*</value>
      <webElementGuid>836bea65-b480-4e13-b1a6-3d9161d1eed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>a8889b43-1bf4-4f22-8ddc-6c7cd1442458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l5_0-87_0-Input_Credit</value>
      <webElementGuid>97eb90ab-8897-4c6b-9137-c5fc32e0a941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l5_0-87_0-Input_Credit&quot;)</value>
      <webElementGuid>192e9822-851f-4556-81be-654b28d6ddb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='l5_0-87_0-Input_Credit']</value>
      <webElementGuid>6ba6f381-e39e-4cb6-a92d-7059757f4d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TransactionDetail']/table/tbody/tr/td[3]/div/span/input</value>
      <webElementGuid>c777657a-1750-407d-837e-1dbdc88cf464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/span/input</value>
      <webElementGuid>d267375d-298e-4f40-96ef-7ad3316d823b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'l5_0-87_0-Input_Credit']</value>
      <webElementGuid>1df5c5d9-204a-49a4-bca0-a20bd44e1726</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
