<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cash in Bank - BPI - Demand Deposit (8_836550</name>
   <tag></tag>
   <elementGuidId>7a6cc363-d92a-4703-9a3c-044e89b95812</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vscomp-option-5306-64']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vscomp-option-5306-64 > span.vscomp-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f3b74d3c-d505-4aff-a9f8-247782ef6ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vscomp-option-text</value>
      <webElementGuid>2c8282dc-79cd-44c7-8089-c4e3393e6b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>Cash in Bank - BPI - Demand Deposit (8881-0045-19) {1-11-111-1}</value>
      <webElementGuid>9f79c95b-3317-47a2-ab85-54ca10e8c39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-enter-delay</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>3ab5a6d2-471e-483c-9627-c02c6b5d6a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-z-index</name>
      <type>Main</type>
      <value>251</value>
      <webElementGuid>84c35b13-db9d-430f-9ad8-1bfbdbd79329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-font-size</name>
      <type>Main</type>
      <value>14px</value>
      <webElementGuid>3e79e955-cbbb-46ab-a5b7-a1779e151b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-alignment</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>0149a40d-83b3-4d04-91c5-1cf8e80dc204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-max-width</name>
      <type>Main</type>
      <value>300px</value>
      <webElementGuid>eca53372-3270-44f4-b850-5c0655d2072b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-ellipsis-only</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1c51cb08-3a99-4f89-bd3f-51d866fb4087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-allow-html</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b141c4c9-95cb-47af-a93a-4bd39ee21025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Cash in Bank - BPI - Demand Deposit (8881-0045-19) {1-11-111-1}
          </value>
      <webElementGuid>7cbc4eb1-6e0c-4b6d-9801-9d7f0b8a3140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vscomp-option-5306-64&quot;)/span[@class=&quot;vscomp-option-text&quot;]</value>
      <webElementGuid>210463ae-5e5c-4da6-a4ff-ef0e6d09ded4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vscomp-option-5306-64']/span</value>
      <webElementGuid>1981de0d-d012-4aad-8c6f-896229aefd43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/following::span[1]</value>
      <webElementGuid>b588dec4-178b-46b0-b569-6d89353b6af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No results found'])[1]/following::span[3]</value>
      <webElementGuid>c87d2a01-1c36-41ae-b09b-e0637d83f0ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash in Bank - BPI - Dollar Account - Savings (8884-0213-33) {1-11-111-2}'])[1]/preceding::span[1]</value>
      <webElementGuid>c0ed4138-f56a-4d0a-8fcf-af5e1a46600f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash in Bank - BPI - Dollar Account - Time Deposit {1-11-111-11}'])[1]/preceding::span[2]</value>
      <webElementGuid>744f0ef1-78e6-43c3-a4cc-e08c74b426a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cash in Bank - BPI - Demand Deposit (8881-0045-19) {1-11-111-1}']/parent::*</value>
      <webElementGuid>e89ff2eb-6878-4687-8905-2a844c9b83ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div[2]/div/div/span</value>
      <webElementGuid>69928ae9-1aa0-4b7e-a306-d87decbd8aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
            Cash in Bank - BPI - Demand Deposit (8881-0045-19) {1-11-111-1}
          ' or . = '
            Cash in Bank - BPI - Demand Deposit (8881-0045-19) {1-11-111-1}
          ')]</value>
      <webElementGuid>26bbd09a-d849-48bb-8927-159ca7f87095</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
