<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_T</name>
   <tag></tag>
   <elementGuidId>b3177df7-1160-45fa-8a03-a637746c5bda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='TextArea_Particulars']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TextArea_Particulars</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b44b631e-192a-4172-907d-3e1324c63dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>11d07b14-6b9d-4fa7-a06b-c7869dc082a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>257ea074-26af-4774-96ba-4cbae956f181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>f416f7e8-3487-4d45-80ed-f17b44c639b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextArea_Particulars</value>
      <webElementGuid>0b98db88-dbdc-4f72-8345-10e3b65c8a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>T</value>
      <webElementGuid>9231e36e-36b7-4ec5-aaa3-f94abe530bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextArea_Particulars&quot;)</value>
      <webElementGuid>2c6ea023-d21f-4e87-8fc5-c67c93de0689</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='TextArea_Particulars']</value>
      <webElementGuid>2986414d-6e8e-4e19-984b-910e2d7bd684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ParticularInput']/span/textarea</value>
      <webElementGuid>e521b0bb-4105-453b-8c91-a45967d318c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Particulars'])[1]/following::textarea[1]</value>
      <webElementGuid>b5c5a491-cbae-4671-ab59-3022264a9915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Number'])[1]/following::textarea[1]</value>
      <webElementGuid>d4d42d89-bf9b-4413-805a-6d893047ae4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Title'])[1]/preceding::textarea[1]</value>
      <webElementGuid>e458eee3-cbb4-40c2-aaaf-196b768fa6bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debit'])[1]/preceding::textarea[1]</value>
      <webElementGuid>57e20f15-2cfc-4d73-83f9-760928ed3dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='T']/parent::*</value>
      <webElementGuid>c219f2b0-8409-45ba-9033-842a3c351ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>cdf7bf35-00e5-4323-92a8-00977af08f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'TextArea_Particulars' and (text() = 'T' or . = 'T')]</value>
      <webElementGuid>c19a00aa-17d5-4fde-9e87-fb9ee3edcc7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
