<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Journal</name>
   <tag></tag>
   <elementGuidId>15c3f4d9-bd7e-48e6-92d9-2e51a77652fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b4-Menu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b4-Menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>39dc176f-cabc-468b-a579-0683bc9e683d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header__item</value>
      <webElementGuid>d44470c9-23ef-49b5-844e-a113c20f4f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b4-Menu</value>
      <webElementGuid>bb603356-3d28-49c8-ae47-e933fbe89743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Journal</value>
      <webElementGuid>1533158b-c0a3-4b4d-9765-15c1dadd9518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b4-Menu&quot;)</value>
      <webElementGuid>d7b6ab6a-e4ff-4988-86af-8f97029b6b6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b4-Menu']</value>
      <webElementGuid>9fe3c2cb-0042-429a-8dd6-2b5820dbc057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b4-SubMenuHeader']/div</value>
      <webElementGuid>58c8699b-f7d8-4de9-9fc0-1f8dd2c2c9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounts'])[1]/following::div[8]</value>
      <webElementGuid>1a594907-50cd-46d7-804f-5a6e465f8dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::div[16]</value>
      <webElementGuid>a8dfbafd-8c51-417b-b949-3936efc9af0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual Entries'])[2]/preceding::div[2]</value>
      <webElementGuid>1a34b529-99fe-4eca-9b52-af64c2ffd31d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>19742a22-cdeb-4a66-b381-c61051be216b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b4-Menu' and (text() = ' Journal' or . = ' Journal')]</value>
      <webElementGuid>9a87c01d-0401-472b-8f67-3942fe53c8f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
