<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Utilities</name>
   <tag></tag>
   <elementGuidId>08e8606a-3764-4866-8b76-553ece619be0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b11-Title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b11-Title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>691d9ab0-3926-4661-8c82-57c935d37dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-accordion-item__title__placeholder</value>
      <webElementGuid>2ba5b9ce-20ca-453d-8bcc-484fdbe2d608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b11-Title</value>
      <webElementGuid>9fb60c71-232e-4dbc-b800-9e19bb1cf471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Utilities</value>
      <webElementGuid>6cda2cae-c540-4878-b6b2-5d315271c6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b11-Title&quot;)</value>
      <webElementGuid>aa863035-d3ab-4a90-a84a-031d77b87d6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b11-Title']</value>
      <webElementGuid>7211f110-dd69-4087-a9f2-a2ae8f11ebed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b11-TitleWrapper']/div</value>
      <webElementGuid>28438f19-4545-4466-b50c-4304922b103c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audit Trail'])[1]/following::div[4]</value>
      <webElementGuid>f83a7c8d-0fe2-4c00-b562-703a320b05b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Logs'])[1]/following::div[4]</value>
      <webElementGuid>a026f59e-a9b8-4a5b-98ed-209f0be38100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Utilities'])[2]/preceding::div[3]</value>
      <webElementGuid>8f11fbb8-434f-4508-a401-26b402d3ea07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div</value>
      <webElementGuid>2a610a95-c0c0-4fb6-976f-352160bdb740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b11-Title' and (text() = ' Utilities' or . = ' Utilities')]</value>
      <webElementGuid>b0395587-8a18-4480-b3ab-15ee2992eced</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
