<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cut-off MonthNo. Of Days</name>
   <tag></tag>
   <elementGuidId>a0944b45-8462-40c7-8456-7122f5684b14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b17-b2-Column1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b17-b2-Column1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c2617006-97b1-4c3f-a0ab-708e64403cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columns-item</value>
      <webElementGuid>623ab5b3-90bc-43c6-bf26-d5f14ece3f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b17-b2-Column1</value>
      <webElementGuid>e961568d-96f8-43a2-9d7a-e8643a09af47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cut-off Month:No. Of Days:</value>
      <webElementGuid>f3445dbe-c5c5-4e0e-bc90-eac742076162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b17-b2-Column1&quot;)</value>
      <webElementGuid>691856ef-21ba-4e3d-87ab-796703afae2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b17-b2-Column1']</value>
      <webElementGuid>4905fad4-7453-4566-b4ac-f8fc6d8d6ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b17-$b2']/div/div</value>
      <webElementGuid>23c4472a-e6cf-4771-a7c3-e793f823da07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Cut-Off'])[1]/following::div[4]</value>
      <webElementGuid>72887991-dd1f-4e5d-a4bb-ca4b72f65143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[1]/following::div[7]</value>
      <webElementGuid>94ccfa21-fcf1-4861-bc1b-25f2ec576fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div/div/div/div/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>6249c78c-cb90-4192-a80d-3482b4569b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b17-b2-Column1' and (text() = 'Cut-off Month:No. Of Days:' or . = 'Cut-off Month:No. Of Days:')]</value>
      <webElementGuid>b8bbebdc-845f-4480-a97f-8dc162207013</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
