<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Create Position_icon fa fa-times-circle fa-2x</name>
   <tag></tag>
   <elementGuidId>4c84cd66-92f7-4150-9327-8031629a4e1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b23-Column2']/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-times-circle.fa-2x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7308c4bf-ce08-461f-9f9b-8bc34b5d3cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-times-circle fa-2x</value>
      <webElementGuid>6062bc31-5748-42b7-9a0b-e12ee4278ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b23-Column2&quot;)/div[1]/a[1]/i[@class=&quot;icon fa fa-times-circle fa-2x&quot;]</value>
      <webElementGuid>b8b43158-1962-4b37-8a32-c4532b0550a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b23-Column2']/div/a/i</value>
      <webElementGuid>6be316b3-66f5-44ae-a224-9f550fb55b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/a/i</value>
      <webElementGuid>030215f5-cfcc-4865-bfd1-dc6d72c75e88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
