<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Rili,Jonna Administrator_icon fa fa-user fa-2x</name>
   <tag></tag>
   <elementGuidId>4ce8b5ba-00b5-42f2-afe3-78e63a356fa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-b2-$b1']/div/div[2]/div[3]/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-user.fa-2x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5fa9db98-1e9f-4598-93f6-092948207c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-user fa-2x</value>
      <webElementGuid>aa3c2c51-c799-43fb-b8fa-08001dc5f97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-b2-$b1&quot;)/div[@class=&quot;user-info&quot;]/div[@class=&quot;margin-left-s ThemeGrid_Margin4First&quot;]/div[@class=&quot;popover custom-popover&quot;]/div[@class=&quot;popover-top&quot;]/div[1]/i[@class=&quot;icon fa fa-user fa-2x&quot;]</value>
      <webElementGuid>b48d9eb1-fdf4-4e1b-95a9-82c923f7e948</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-b2-$b1']/div/div[2]/div[3]/div/div/i</value>
      <webElementGuid>9abd665d-488a-48c5-8f89-2b35267e1097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/i</value>
      <webElementGuid>c3abeab3-7c53-41d6-97c1-c5514326b3a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
