<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Position</name>
   <tag></tag>
   <elementGuidId>82b92f84-73a7-47f8-97d4-3dcf27ceb0b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b11-Title']/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b11-Title > div > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>51abcbc2-3d48-4854-9011-44d3e2f6a7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Position</value>
      <webElementGuid>1d9cc6ad-d546-4841-bc51-a8ce2273876c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b11-Title&quot;)/div[1]/span[1]</value>
      <webElementGuid>afe3a26d-e5d2-4308-b5b1-884c6702b987</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b11-Title']/div/span</value>
      <webElementGuid>9414d73b-92e0-4d80-bb62-1b4c7568c4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reference Type'])[1]/following::span[1]</value>
      <webElementGuid>efb5f5b5-aa03-4a12-b03f-9888adb07f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved and Limit'])[1]/following::span[2]</value>
      <webElementGuid>2d343b80-83c8-4be6-8410-e6c6374bc3b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barangay'])[1]/preceding::span[1]</value>
      <webElementGuid>d399bec4-ae81-4d96-91aa-1bf30fc64e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/preceding::span[2]</value>
      <webElementGuid>f59b1e75-6119-4276-a681-3b734b01a4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Position']/parent::*</value>
      <webElementGuid>b7f27295-f7b8-4ec0-a7ec-9742b7628f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/span</value>
      <webElementGuid>c5206597-dd00-4d55-91f2-a670b3333a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Position' or . = 'Position')]</value>
      <webElementGuid>b393cc6d-9a9c-4747-815a-15d235715746</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
