<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create Position</name>
   <tag></tag>
   <elementGuidId>0d02018d-e9c9-4a8e-ba39-d8aa760482c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Button3']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Button3 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5119f8f8-c19e-4d8a-9438-fa86034986d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Create Position</value>
      <webElementGuid>e569fdf4-8454-467c-b067-fd20a23ed609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Button3&quot;)/span[1]</value>
      <webElementGuid>dd2c7b91-485e-4447-952b-d71240bee40d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='Button3']/span</value>
      <webElementGuid>797a00be-34a3-4ec3-a9c1-e10f568836d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='items'])[3]/following::span[5]</value>
      <webElementGuid>126f2ba7-1a3e-4f3e-88b2-1c1946f102fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of'])[4]/following::span[7]</value>
      <webElementGuid>a69d0cc4-a40f-4b37-9f7d-171afb269800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[3]/preceding::span[1]</value>
      <webElementGuid>a835f03d-780d-42ec-a04d-74aee5341655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Position'])[3]/preceding::span[3]</value>
      <webElementGuid>291eba60-cefa-4552-857c-1fcfa4b91f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/article/div/div/div/div/button/span</value>
      <webElementGuid>b048f794-e3ee-4a5c-bf33-2823bd961589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Create Position' or . = ' Create Position')]</value>
      <webElementGuid>410ae929-81ea-4c75-9c97-4dcf5761d188</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
