<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create City</name>
   <tag></tag>
   <elementGuidId>ac77c1ae-0b9c-4eea-9589-feea07321747</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Button2']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Button2 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>aba0ad54-c936-4542-8b20-585facede3dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Create City</value>
      <webElementGuid>6adaba16-6890-40c6-af3f-48ed90cccf67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Button2&quot;)/span[1]</value>
      <webElementGuid>fc69fc3f-d6be-46bc-a9c9-aa024d937a8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='Button2']/span</value>
      <webElementGuid>1cc26cbc-7071-46d4-a66c-219e985090e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='items'])[5]/following::span[1]</value>
      <webElementGuid>11909da7-b263-4cb7-a996-d267b9d1f9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of'])[6]/following::span[3]</value>
      <webElementGuid>40bdcf60-90b5-4318-b369-1981ccc8c365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[5]/preceding::span[1]</value>
      <webElementGuid>a87d8260-0e57-4884-b281-49a03515b240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[2]/preceding::span[3]</value>
      <webElementGuid>2cbe65f0-305d-423a-b8d1-7466401c48d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/article/div/div/div/div/button/span</value>
      <webElementGuid>1e571cf4-3a24-46f6-a322-4bfca6e96b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Create City' or . = ' Create City')]</value>
      <webElementGuid>77555c61-dbc0-4544-b96a-80503ccf1b82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
