<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manual Entries</name>
   <tag></tag>
   <elementGuidId>750492ee-748b-42a9-90ba-1545a1343e7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='b2-ManualEntries2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-ManualEntries2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8aa382fd-8f67-4934-9430-51e9d9303e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/AccountingSystem/ManualEntries</value>
      <webElementGuid>25a0f6c0-ae84-4900-86dd-c95b88d3666a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-ManualEntries2</value>
      <webElementGuid>143779d1-4d07-4643-a7b3-3fafa0b3675f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>a3858cc6-802f-4d88-884f-36c84328502d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0971ad42-9b2c-4441-8983-5d8cff422021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manual Entries</value>
      <webElementGuid>d47f1e2d-4a83-4fee-a44c-dedbe7483735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-ManualEntries2&quot;)</value>
      <webElementGuid>aef345a4-d1e1-4546-84fa-56138f2b0755</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='b2-ManualEntries2']</value>
      <webElementGuid>2f4eea48-f094-4595-999b-eecfd9751f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b4-Items']/a</value>
      <webElementGuid>4bfa32e2-049b-4006-9b85-e98fd30358c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Journal'])[1]/following::a[1]</value>
      <webElementGuid>943f392e-f79d-4095-b2a5-dc9467fbae01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounts'])[1]/following::a[1]</value>
      <webElementGuid>409cc447-b2a9-4f7a-9e8b-fc6eda715440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Details'])[1]/preceding::a[1]</value>
      <webElementGuid>f1155d1e-d718-445f-a71e-afd124fb5640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/AccountingSystem/ManualEntries')]</value>
      <webElementGuid>c664d6cc-bcd6-4580-b5da-869d37555374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>3150c916-8f94-48cd-b49a-e550a01299ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/AccountingSystem/ManualEntries' and @id = 'b2-ManualEntries2' and (text() = 'Manual Entries' or . = 'Manual Entries')]</value>
      <webElementGuid>8c5a82f2-a4c0-455c-b0d8-89347c94f604</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
