<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Sign-in continue session_notview</name>
   <tag></tag>
   <elementGuidId>e16907c8-73db-4d08-b223-40d1a69031e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#notview</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='notview']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f6e2f91f-d094-46e5-b6ea-1273374644a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-eye-slash fa-2x</value>
      <webElementGuid>1330a6b2-200b-4215-a0ad-dda78cd08393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notview</value>
      <webElementGuid>309c8a47-77c3-4c30-bc83-197f671d5e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notview&quot;)</value>
      <webElementGuid>34867c18-0669-4ca4-b9dc-dcb65292d6e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='notview']</value>
      <webElementGuid>8c55d1be-1819-484d-98e0-011ad17321ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-Column2']/div/a/i</value>
      <webElementGuid>c03c37fc-a480-4852-bf5d-7184b7939f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>74e81d8d-38b9-4481-a22d-00cb84006edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'notview']</value>
      <webElementGuid>9e6ea017-16d6-4d31-ab6b-9ab9a5ea2b77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
