<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign-in continue session_Input_Password</name>
   <tag></tag>
   <elementGuidId>a62aca3e-9024-41ff-815d-0f32a10c5e24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_Password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_Password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28dc2bb7-d467-4997-9f79-2506964c86a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control login-password OSFillParent</value>
      <webElementGuid>e494c9cf-3540-42c9-b219-cc9a0917bc8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1072e1a6-fb6b-4ee3-a623-17f05194f5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Password</value>
      <webElementGuid>e15e55d8-7e99-48f4-9108-dcfa51f3aeec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>df655a97-abef-425d-80aa-20c62559297c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_Password</value>
      <webElementGuid>c34b830a-c3ff-46ce-a509-cd527142b51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_Password&quot;)</value>
      <webElementGuid>e71541d9-1229-450d-ae33-c5f0122c6c64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_Password']</value>
      <webElementGuid>1158f474-c46b-47d2-92e7-12376e474786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-Input']/span/input</value>
      <webElementGuid>4f5f88b0-f6a1-4200-932d-e73b7a3d6473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[2]/span/input</value>
      <webElementGuid>72ec329a-5d0e-4f50-abe9-189c8c4cd26f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Enter Password' and @id = 'Input_Password']</value>
      <webElementGuid>7020c7ee-9414-47d1-97f2-b9fa7b776b44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
