<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Accounts</name>
   <tag></tag>
   <elementGuidId>62d0b5f7-d2ea-4f37-bbeb-deb13f0e6293</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b3-TitleWrapper']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b3-TitleWrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3708ce38-c17c-45ea-90f0-e40d7212c110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-accordion-item__title osui-accordion-item__title--is-right</value>
      <webElementGuid>aa269273-8dd9-4da8-8cfe-8c3fc5b8edc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b3-TitleWrapper</value>
      <webElementGuid>7f6186ef-6445-468c-88db-4d8bd7ec2a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8d1a84ab-0253-4bdd-9d2f-aab18a3eb8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7091f224-e62d-4520-b33e-4a7fa15192d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>01581cba-ed96-4817-82ca-feee2db3534a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Accounts</value>
      <webElementGuid>f8274542-625e-4f15-8fad-ba29b7bfa221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b3-TitleWrapper&quot;)</value>
      <webElementGuid>c3816c08-0314-44d5-bfb7-57daac5a9437</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b3-TitleWrapper']</value>
      <webElementGuid>6def5f60-3759-405e-8554-6d393d20cb21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b3-AccordionItem']/div</value>
      <webElementGuid>4ffc2dc3-a10d-4d29-a734-40f35eb517cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::div[7]</value>
      <webElementGuid>8f7fae71-e2d8-40fc-9680-593e299d3822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCOUNTING SYSTEM'])[1]/following::div[9]</value>
      <webElementGuid>128e7e38-f96f-4722-9e33-7a9a91f8865d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Journal'])[1]/preceding::div[4]</value>
      <webElementGuid>fecce9b6-3f78-4027-8d06-8bbf75bb4b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>99892289-b981-4bb2-9b48-1af240834606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b3-TitleWrapper' and (text() = ' Accounts' or . = ' Accounts')]</value>
      <webElementGuid>976b2a88-484a-4598-9d62-ff1b790ef6d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
