<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Utilities</name>
   <tag></tag>
   <elementGuidId>2acb84da-0869-4e28-8621-74d0c6093880</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b11-Title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b11-Title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cf89711a-bb73-45d0-9834-bc8e85d8e080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-accordion-item__title__placeholder</value>
      <webElementGuid>f4f8ce73-ec33-4e16-b963-bade91ad8eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b11-Title</value>
      <webElementGuid>309a554d-8de4-46f4-80df-d31404e0d6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Utilities</value>
      <webElementGuid>0acaf199-e85f-45f2-9b94-7f90917dadd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b11-Title&quot;)</value>
      <webElementGuid>e4f479b4-8c8f-438c-9bae-69f4774133de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b11-Title']</value>
      <webElementGuid>15aca1a3-21ad-4b71-bd31-38c8adf3403d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b11-TitleWrapper']/div</value>
      <webElementGuid>50d32cfc-9702-4cbf-a7bf-45f14c9f06a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audit Trail'])[1]/following::div[4]</value>
      <webElementGuid>763c44d8-2d08-4012-b729-ddedf0cf9264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Logs'])[1]/following::div[4]</value>
      <webElementGuid>11b19ef6-fb83-4b71-bc23-ec266b674cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Utilities'])[2]/preceding::div[3]</value>
      <webElementGuid>ec41be9b-6574-4e6a-99a3-58d36b042729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div</value>
      <webElementGuid>453e9799-b45d-4071-b900-0e5efda81d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b11-Title' and (text() = ' Utilities' or . = ' Utilities')]</value>
      <webElementGuid>40976a94-543d-40a2-9112-21c33cf01ca1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
