<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Force Logout_icon fa fa-times fa-2x</name>
   <tag></tag>
   <elementGuidId>dcd9cc3f-cd93-44af-88e4-4bd0512f931d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b16-Column2']/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-times.fa-2x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ceefdba3-60f1-4097-803d-6e1420caed89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-times fa-2x</value>
      <webElementGuid>845f7fa0-5f32-4a90-bd4f-e44ac57ff406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b16-Column2&quot;)/div[1]/a[1]/i[@class=&quot;icon fa fa-times fa-2x&quot;]</value>
      <webElementGuid>6e0a7786-ddfe-473e-a3bc-665223701674</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b16-Column2']/div/a/i</value>
      <webElementGuid>b846dae0-3bbc-42c0-86a0-6f2077e709db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/a/i</value>
      <webElementGuid>9c6f1ed8-9a6b-4bb9-bb10-02c5a8656a71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
