<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_User Management Form_icon fa fa-times-cir_4adfb2</name>
   <tag></tag>
   <elementGuidId>1120f40e-8c98-4e0f-ad68-77c39b376f6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Close']/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-times-circle.fa-2x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4d2e5f5d-0412-4a6b-bfb5-77d288b690f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-times-circle fa-2x</value>
      <webElementGuid>efc1c5cd-79ac-495e-8de8-3ac589a5fe1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Close&quot;)/a[1]/i[@class=&quot;icon fa fa-times-circle fa-2x&quot;]</value>
      <webElementGuid>3917d945-34e3-46c5-a9ec-25ed5506f7c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Close']/a/i</value>
      <webElementGuid>efa06a55-3a07-4b09-9b0e-b9455eb51e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/a/i</value>
      <webElementGuid>78c0b1eb-0c25-4d6e-80b1-349734bf9daf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
