<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Accounts</name>
   <tag></tag>
   <elementGuidId>65d8595f-1218-401a-9270-6619826b5538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b3-Title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b3-Title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>82447add-dde6-4b9b-8367-d6d111d2c76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-accordion-item__title__placeholder</value>
      <webElementGuid>a531d239-6703-43fe-8e6a-dde50895f9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b3-Title</value>
      <webElementGuid>dcd14584-9fac-43dd-b625-440af5cb570e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Accounts</value>
      <webElementGuid>3b69b738-9723-439b-8ec5-f89c3463b08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b3-Title&quot;)</value>
      <webElementGuid>5e3a14f7-09c9-461f-bea0-198c75d1bde0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b3-Title']</value>
      <webElementGuid>6085b3ff-d98b-4fc0-97e2-cbb22448b2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b3-TitleWrapper']/div</value>
      <webElementGuid>fb6c3a0b-4c6d-431b-9ee6-d9a2bb13b0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::div[8]</value>
      <webElementGuid>9d02cc86-cf08-4d92-b5ce-c07722ed3552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCOUNTING SYSTEM'])[1]/following::div[10]</value>
      <webElementGuid>5c24a72e-7126-4885-8c24-1759acb1aee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Journal'])[1]/preceding::div[3]</value>
      <webElementGuid>fc2c1dba-0646-43ac-9e05-93e895abdd8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>fab7c31b-ecc2-4857-9a55-df0e535d6ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b3-Title' and (text() = ' Accounts' or . = ' Accounts')]</value>
      <webElementGuid>e9c9bbe5-46d7-49e8-8334-14b0bf9b9730</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
