<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Action_icon fa fa-plus-square fa-2x</name>
   <tag></tag>
   <elementGuidId>4173056a-ae26-49f2-b85c-285f5ccb31d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-plus-square.fa-2x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='TableWidgetId2']/tbody/tr/td/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d1c530e7-4419-4b85-82d3-ea6a12ab2eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-plus-square fa-2x</value>
      <webElementGuid>8a70b9c2-7242-45a8-b59c-fb0b46418f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TableWidgetId2&quot;)/tbody[1]/tr[@class=&quot;table-row&quot;]/td[1]/a[1]/i[@class=&quot;icon fa fa-plus-square fa-2x&quot;]</value>
      <webElementGuid>9e47e7e1-deba-47d4-afdd-ea7ae990abce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='TableWidgetId2']/tbody/tr/td/a/i</value>
      <webElementGuid>65e199c2-8a21-4dfb-b8cd-3fd0532bd4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a/i</value>
      <webElementGuid>5c2ccc06-6132-47cc-bdc9-a3ff724ce205</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
