<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Series Number_icon fa fa-th fa-2x</name>
   <tag></tag>
   <elementGuidId>5691e80b-5a1a-44c0-8ad6-8f55710c978d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-th.fa-2x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-b2-$b1']/div/div/div[2]/div/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a0d97561-546b-434c-9569-153ecbf9c0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-th fa-2x</value>
      <webElementGuid>a21dd3eb-fec7-4016-9d53-db097f14137a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-b2-$b1&quot;)/div[@class=&quot;user-info ThemeGrid_Margin10First&quot;]/div[@class=&quot;margin-left-s&quot;]/div[@class=&quot;popover custom-popover&quot;]/div[@class=&quot;popover-top&quot;]/div[@class=&quot;ThemeGrid_Margin3First&quot;]/div[1]/i[@class=&quot;icon fa fa-th fa-2x&quot;]</value>
      <webElementGuid>fd6b03ae-d6a0-4b3c-81ab-31ef5009de58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-b2-$b1']/div/div/div[2]/div/div/div/i</value>
      <webElementGuid>8bcd24c6-72f5-49e6-9265-4e065bf37962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div/div[2]/div/div/div/i</value>
      <webElementGuid>55a5b633-fcda-439e-9d67-5893085243a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
