<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_User Management</name>
   <tag></tag>
   <elementGuidId>dd413f34-9e47-4980-8ced-6e871389f389</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-UserManagement2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='b2-UserManagement2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de0b2f55-8981-4c7a-b66d-66d93e6c4dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/AccountingSystem/ManageUser?UserDetailsId=0&amp;userid=0</value>
      <webElementGuid>940041c0-fe78-477b-82a4-e7c87b711db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-UserManagement2</value>
      <webElementGuid>598c8c21-0c04-486f-bd6a-5ab6fc5d3391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>59f76e99-c78d-4a0e-8f4f-0fae89ba87ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>adc7d3a5-a6bf-421f-8b7b-31f7f1352b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User Management</value>
      <webElementGuid>d05a8c4f-187d-441d-a6c0-c629e42a2462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-UserManagement2&quot;)</value>
      <webElementGuid>944200d6-9685-4bd4-bd91-ae0e67a1d723</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='b2-UserManagement2']</value>
      <webElementGuid>a7ff72fa-034e-4c96-a1f8-d09f0b6886fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b12-Items']/a</value>
      <webElementGuid>ad7728b9-d842-49ea-ad58-00daa137c43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'User Management')]</value>
      <webElementGuid>a9c8ebb0-2b42-4c1e-a66c-caddb4de7267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Utilities'])[2]/following::a[1]</value>
      <webElementGuid>b13ac1eb-269b-479e-a1c9-b2d548e322e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Utilities'])[1]/following::a[1]</value>
      <webElementGuid>d7ec76b5-84c5-4016-8f66-ab74afed14e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Roles'])[1]/preceding::a[1]</value>
      <webElementGuid>b5988c88-1c47-4d9d-b554-2f55fa646f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Parameter'])[1]/preceding::a[2]</value>
      <webElementGuid>728b02bb-3c14-46da-be47-42726ea2af45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User Management']/parent::*</value>
      <webElementGuid>858796d1-d752-4380-80b2-36e314ce1edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/AccountingSystem/ManageUser?UserDetailsId=0&amp;userid=0')]</value>
      <webElementGuid>1baebe17-4b21-4ce8-959e-028b967562c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div[2]/a</value>
      <webElementGuid>2a5ce124-36eb-4bbd-b8fe-ad755b5f0116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/AccountingSystem/ManageUser?UserDetailsId=0&amp;userid=0' and @id = 'b2-UserManagement2' and (text() = 'User Management' or . = 'User Management')]</value>
      <webElementGuid>e7dfb345-d463-44fe-acda-32ce40a414e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
