<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Utilities</name>
   <tag></tag>
   <elementGuidId>d81cb37e-0a55-46cf-9f6e-242c68e5eaed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b11-TitleWrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b11-TitleWrapper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2a4046a7-c274-4731-bad1-2dd60fe998ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-accordion-item__title osui-accordion-item__title--is-right</value>
      <webElementGuid>4536be90-9add-4c97-8be2-70832e68155d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b11-TitleWrapper</value>
      <webElementGuid>89894b0e-9ac1-4370-9cf1-0ede620d2279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ff7d89ad-c794-49e9-9461-a5505b616fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d1e4d70b-5621-43c0-8d62-3d6ad5e4f8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>08a9e015-1136-4747-99da-c6109e70fb70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Utilities</value>
      <webElementGuid>46891cf7-6a27-4f70-a7ba-209c843404a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b11-TitleWrapper&quot;)</value>
      <webElementGuid>9ea72765-903b-456c-a941-e41f63c9684d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b11-TitleWrapper']</value>
      <webElementGuid>5fe22a04-0856-4851-b913-5dc49b34bca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b11-AccordionItem']/div</value>
      <webElementGuid>f842851b-2a3d-42c3-b4b0-34e578d783b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audit Trail'])[1]/following::div[3]</value>
      <webElementGuid>a8d8dd5d-13f9-4d46-8b44-359817ed1da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Logs'])[1]/following::div[3]</value>
      <webElementGuid>3c21dca3-eb45-4472-ba07-725aca72df76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Utilities'])[2]/preceding::div[4]</value>
      <webElementGuid>522b781f-d8e4-4fac-b92a-1ad11487c169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/div/div</value>
      <webElementGuid>868d8e1b-78ec-496e-bd2d-b75eefa2fa0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b11-TitleWrapper' and (text() = ' Utilities' or . = ' Utilities')]</value>
      <webElementGuid>5a9859bf-0656-47c2-bb5a-1c65b904f1d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
