<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Accounts</name>
   <tag></tag>
   <elementGuidId>a8eb2f66-0d3b-498f-950a-8a39c70beac4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b3-Title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b3-Title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>249ad3ba-e3ce-4734-8ded-90fc9aab9a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-accordion-item__title__placeholder</value>
      <webElementGuid>3338c4bf-eeae-411d-914a-4c044314ab1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b3-Title</value>
      <webElementGuid>e1739268-58e3-41b4-bfbb-fd88ea5368e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Accounts</value>
      <webElementGuid>4598970a-f89a-4a28-a5af-a8d9dcc85e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b3-Title&quot;)</value>
      <webElementGuid>fc36e734-7ddc-431b-b591-2aa5620d7b9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b3-Title']</value>
      <webElementGuid>e5f18b9d-dd28-41d5-8d0d-6cdee722e192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b3-TitleWrapper']/div</value>
      <webElementGuid>45a41a21-6cb4-45c8-b57d-dec48c3ee12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::div[8]</value>
      <webElementGuid>8067ba9e-f8af-47fe-9cc4-11d184315004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrator'])[1]/following::div[11]</value>
      <webElementGuid>8e88346e-de21-4eec-b50a-6a871a0fc601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Journal'])[1]/preceding::div[3]</value>
      <webElementGuid>dde83dd0-6bae-4678-966f-b39a3eccb555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>1eed98ff-71de-44ca-a05a-05892cb7d93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b3-Title' and (text() = ' Accounts' or . = ' Accounts')]</value>
      <webElementGuid>7a2beb99-c369-44de-a424-1704b19b661f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
