<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Accounts_osui-accordion-item__icon osui_cac4c0</name>
   <tag></tag>
   <elementGuidId>c2a72ab9-89b4-4e67-b657-2f3401efcf65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.osui-accordion-item__icon.osui-accordion-item__icon--caret</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b3-TitleWrapper']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2b83a14c-db71-47cf-9998-ca2823487704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-accordion-item__icon osui-accordion-item__icon--caret</value>
      <webElementGuid>97fec871-0750-4be8-82a9-250c09d21fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a94e2ea5-e97f-4e23-80e2-f422eb486e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b3-TitleWrapper&quot;)/div[@class=&quot;osui-accordion-item__icon osui-accordion-item__icon--caret&quot;]</value>
      <webElementGuid>9bac5e53-e024-4248-896c-f84fd9f56467</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b3-TitleWrapper']/div[2]</value>
      <webElementGuid>baae5054-3a14-4f2c-8773-91ef74456c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>fc04c5cf-f5f5-4ddd-869a-3508aebf2c82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
