<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Journal</name>
   <tag></tag>
   <elementGuidId>e9296409-d39a-4951-8a38-b9612ccfd888</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b4-Menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b4-Menu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6ffd7edf-124d-493c-a282-c840424bd267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header__item</value>
      <webElementGuid>b31ba6bc-6a62-4f3b-949e-3d450fab8764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b4-Menu</value>
      <webElementGuid>bfb31916-7ede-46c4-95d7-21b506d0bf26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Journal</value>
      <webElementGuid>1252d091-e5b1-431d-a6b4-b499f754f176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b4-Menu&quot;)</value>
      <webElementGuid>008e00a7-72fe-4bfd-b70b-e35653fe5326</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b4-Menu']</value>
      <webElementGuid>19baea13-874d-4808-979d-8ee74c74d793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b4-SubMenuHeader']/div</value>
      <webElementGuid>0fe08021-eea7-471b-8bd2-0923704be18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounts'])[1]/following::div[8]</value>
      <webElementGuid>d1ae4ecb-0fa2-4b7a-afe5-7491e74335b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::div[16]</value>
      <webElementGuid>51dc4bbc-2286-4df9-a5b6-decc5889e3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual Entries'])[1]/preceding::div[2]</value>
      <webElementGuid>6774017e-9360-410f-9c6e-c820097ebe07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>64451895-b429-44aa-a1e7-3270bed02bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b4-Menu' and (text() = ' Journal' or . = ' Journal')]</value>
      <webElementGuid>500f2e48-0ea4-4bd3-bf86-091e250c9d67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
