<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CAS Accounts</name>
   <tag></tag>
   <elementGuidId>43917ce8-53f3-4928-a848-59ecaea3d747</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b6-Menu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b6-Menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>34eeff67-22cf-481e-9d3c-eab5b3219c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header__item</value>
      <webElementGuid>fabc5b07-9ef4-4c8a-8dc0-aca57f4de62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b6-Menu</value>
      <webElementGuid>4b81f3c8-1f9a-4d1f-9315-1de3dbfcee31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CAS Accounts</value>
      <webElementGuid>3f73b8e1-4bd1-4e62-9f10-83e29a43ca27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b6-Menu&quot;)</value>
      <webElementGuid>e7a18c85-a2dd-46d8-a889-634b74b8e420</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b6-Menu']</value>
      <webElementGuid>f46cee5e-8d6b-4e1b-acb3-8d842480655a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b6-SubMenuHeader']/div</value>
      <webElementGuid>deea4741-69b7-4553-ac3f-80c24f34fda0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adjustment Details'])[1]/following::div[4]</value>
      <webElementGuid>360a1762-1dca-4930-9fc1-c21ea9808b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adjustment Entries'])[1]/following::div[4]</value>
      <webElementGuid>ef6eca47-7a4b-46c8-821e-c410823502d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batch Upload'])[1]/preceding::div[3]</value>
      <webElementGuid>3c89e5e4-4cb8-4cf6-8a5a-484b75b10b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div/div</value>
      <webElementGuid>98122da7-a066-42e2-a9a4-beb8595e0e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b6-Menu' and (text() = 'CAS Accounts' or . = 'CAS Accounts')]</value>
      <webElementGuid>2aa5ea91-2420-4de0-a7f0-5fe448a2eb57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
