<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Accounts</name>
   <tag></tag>
   <elementGuidId>fe424c4a-bce4-4acf-8631-790dc4fd0cc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b3-TitleWrapper']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b3-TitleWrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>99a2900d-686f-4c53-8ec7-5e48e77f9edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-accordion-item__title osui-accordion-item__title--is-right</value>
      <webElementGuid>c24af93c-bc59-4c7d-a762-593af184c8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b3-TitleWrapper</value>
      <webElementGuid>9961e6d2-7aff-43f2-8fdd-0e8b7051474c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5f1b1d23-7ed5-48ef-85d6-cdbe820cdd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>50f2b933-e69b-4758-9988-2d841135bc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6a4aa47e-c012-44a6-903b-f07f296eb0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Accounts</value>
      <webElementGuid>70e3badc-bcbb-47db-a2fd-58551cf91e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b3-TitleWrapper&quot;)</value>
      <webElementGuid>110d23d4-9c97-40dc-87ba-f2cf54c2f55e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b3-TitleWrapper']</value>
      <webElementGuid>68603c82-1cf8-49f3-b10e-17f1afe8b5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b3-AccordionItem']/div</value>
      <webElementGuid>436afc37-24bc-4a0b-8976-35382648570a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::div[7]</value>
      <webElementGuid>249d4237-eaf7-4362-9e17-20273d59aedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCOUNTING SYSTEM'])[1]/following::div[9]</value>
      <webElementGuid>a85735fb-4e42-457b-83e8-7bb425f60e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Journal'])[1]/preceding::div[4]</value>
      <webElementGuid>43fb0b7b-e8eb-4e2b-9e04-6a1a79a7646d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>7aea3f1d-32f7-4699-87e4-bfc3e0892202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b3-TitleWrapper' and (text() = ' Accounts' or . = ' Accounts')]</value>
      <webElementGuid>a307c0fc-2510-45bf-b3e6-cd6133d6ff81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
