<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CAS Accounts</name>
   <tag></tag>
   <elementGuidId>399d7456-a440-489b-956f-1b8dc8c8d48d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='b2-CASAccounts4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-CASAccounts4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7f62a3c9-c015-41bb-b31f-b170aa16ebde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-CASAccounts4</value>
      <webElementGuid>18d2ff8b-4c78-4b66-9bc4-c32d761b9b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CAS Accounts</value>
      <webElementGuid>55129b45-fe8b-434d-b941-dd492524a5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-CASAccounts4&quot;)</value>
      <webElementGuid>51e6fca1-d99c-47bf-85ba-bc439e06e15e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b2-CASAccounts4']</value>
      <webElementGuid>766b7273-eac0-479a-a6b2-26e7b313d12d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='b2-CASAccounts3']/span</value>
      <webElementGuid>c539bd70-c1cc-4fe3-a0fc-df642e4d1d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adjustment Details'])[1]/following::span[1]</value>
      <webElementGuid>898b42fc-da48-42a0-a334-d770b002bdf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adjustment Entries'])[1]/following::span[2]</value>
      <webElementGuid>dbec70ff-a45b-4684-9b61-b68210e4a49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batch Upload'])[1]/preceding::span[1]</value>
      <webElementGuid>a6e6fa76-d2f6-49fc-a24c-3c123cad58e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual Adjustment EntryBatch Upload'])[1]/preceding::span[2]</value>
      <webElementGuid>19cef05c-5292-4053-9e1f-3f7ee0804f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CAS Accounts']/parent::*</value>
      <webElementGuid>c00b5a7f-73b7-4e3a-b664-17612c3ccf9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a/span</value>
      <webElementGuid>c98d1700-07de-46af-a819-0add0b73ab58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b2-CASAccounts4' and (text() = 'CAS Accounts' or . = 'CAS Accounts')]</value>
      <webElementGuid>a1aa3e8f-4ae9-49aa-84a5-2f92f310a256</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
