<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manual Entries</name>
   <tag></tag>
   <elementGuidId>f48eace6-4bef-4b95-88e0-253dde7d683d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='b2-ManualEntries2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-ManualEntries2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ef193f84-af81-4525-a13a-16eb75805fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/AccountingSystem/ManualEntries</value>
      <webElementGuid>e43890cb-2c11-4cf4-afc1-4e3628b5db1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-ManualEntries2</value>
      <webElementGuid>f8de3143-c682-4ab9-9a8c-7a8dc65bc366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>cbbc8a00-970f-4ca6-a4d3-0e648a156ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f6240254-a539-4c87-a779-d1fbe0dacb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manual Entries</value>
      <webElementGuid>2c20e1b1-98cf-4f12-ac6e-ebc1fd90d0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-ManualEntries2&quot;)</value>
      <webElementGuid>4e061f20-f0f4-42e3-bf7b-4cea7b9c829f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='b2-ManualEntries2']</value>
      <webElementGuid>6369b729-cef2-43ec-8869-7f7ddf3ac830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b4-Items']/a</value>
      <webElementGuid>c14b07f1-2a78-49c4-b9c4-ce2226be6ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Journal'])[1]/following::a[1]</value>
      <webElementGuid>45c9f8e9-9751-4f66-ad28-8060ad008371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounts'])[1]/following::a[1]</value>
      <webElementGuid>c9b39556-1dde-4576-a506-f2d1ed2fafbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Details'])[1]/preceding::a[1]</value>
      <webElementGuid>58863c2b-5240-4062-9277-13160a96b9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/AccountingSystem/ManualEntries')]</value>
      <webElementGuid>3988c10f-55d9-4b3c-882c-306866026994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>1c27d63e-8d49-48e2-8c49-f7392fa8caff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/AccountingSystem/ManualEntries' and @id = 'b2-ManualEntries2' and (text() = 'Manual Entries' or . = 'Manual Entries')]</value>
      <webElementGuid>ba2fbb23-ec94-4278-a4e4-e61358d24c11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
