<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_21</name>
   <tag></tag>
   <elementGuidId>67034961-0822-4ae8-8269-8e6a62406051</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b16-b1-Calendar']/div[2]/div/table/tbody/tr/td/div/div/div[4]/div[2]/table/thead/tr/td[6]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b407aa53-6549-4e4b-9386-ea32ef26edd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fc-day-number</value>
      <webElementGuid>719d65dd-1b2c-4db6-a982-8d517e6828f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>c70f720a-5c6f-4e23-b139-b150c3275051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b16-b1-Calendar&quot;)/div[@class=&quot;fc-view-container&quot;]/div[@class=&quot;fc-view fc-dayGridMonth-view fc-dayGrid-view&quot;]/table[1]/tbody[@class=&quot;fc-body&quot;]/tr[1]/td[@class=&quot;fc-widget-content&quot;]/div[@class=&quot;fc-scroller fc-day-grid-container&quot;]/div[@class=&quot;fc-day-grid&quot;]/div[@class=&quot;fc-row fc-week fc-widget-content fc-rigid&quot;]/div[@class=&quot;fc-content-skeleton&quot;]/table[1]/thead[1]/tr[1]/td[@class=&quot;fc-day-top fc-fri fc-past&quot;]/span[@class=&quot;fc-day-number&quot;]</value>
      <webElementGuid>ebd9af28-1919-4ed7-a7c3-c693e80e884d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b16-b1-Calendar']/div[2]/div/table/tbody/tr/td/div/div/div[4]/div[2]/table/thead/tr/td[6]/span</value>
      <webElementGuid>ddf65c0e-796e-4b1f-b4bf-855290b4112e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::span[27]</value>
      <webElementGuid>80c03bd7-eeb4-4914-bfe2-0c3480c59e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::span[28]</value>
      <webElementGuid>82a5ba6b-87d4-4739-9b4e-428f175c63ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MODE OF TRANSACTION'])[1]/preceding::span[16]</value>
      <webElementGuid>5d537602-cd2c-435c-8033-20f902663b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pie chart with 3 slices.'])[1]/preceding::span[17]</value>
      <webElementGuid>2cf776f8-c7e4-4faf-a1e6-2029b97ff2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='21']/parent::*</value>
      <webElementGuid>562f69d0-f475-402d-ae0c-790c47802f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/table/thead/tr/td[6]/span</value>
      <webElementGuid>4b97c9b7-bbeb-4d9b-a7d6-53567691f2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '21' or . = '21')]</value>
      <webElementGuid>bf406a71-0109-4741-92cc-584249873fe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
