<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LOGIN_Input_Password2</name>
   <tag></tag>
   <elementGuidId>c2f77102-162f-416b-8dce-66cf1245229f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_Password2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Input_Password2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05fa6eac-f7ab-4628-80d0-b4e3ee455892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control login-password</value>
      <webElementGuid>5b249854-66e3-4c2e-92c4-e19bc12e9662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5b207894-f63c-48b5-8640-9f00817429a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Password</value>
      <webElementGuid>5a90cb43-4aeb-44f0-9cec-3c9ad0d8d0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>fd7ad641-5f01-435a-800b-448aa951ddfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_Password2</value>
      <webElementGuid>0117669a-9458-4d39-943a-ca5f81864a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_Password2&quot;)</value>
      <webElementGuid>1bf0accb-031e-4d39-ac40-d204611a5b4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_Password2']</value>
      <webElementGuid>5688f694-b727-44db-895c-934068d9e080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-Input']/span/input</value>
      <webElementGuid>cb15bc87-4eec-4541-baff-f114a1ec939c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>e9115e4b-b282-42ce-b5ff-4b49810d5c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Enter Password' and @id = 'Input_Password2']</value>
      <webElementGuid>3666b4c5-433c-464b-813e-74c70c628146</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
