<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Utilities</name>
   <tag></tag>
   <elementGuidId>29f854e8-272f-46e4-9555-e2e6ff0e866b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b11-Title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b11-Title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f6aa80dc-f3e5-4be2-95d8-d5b43901b563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-accordion-item__title__placeholder</value>
      <webElementGuid>a39b976a-fb45-45a8-b515-cdd3065cc925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b11-Title</value>
      <webElementGuid>4d4a1202-1424-40e6-87c3-a3fc170c2662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Utilities</value>
      <webElementGuid>4f24ca60-2152-4cf2-a06a-631cf5dd4d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b11-Title&quot;)</value>
      <webElementGuid>4eae71e4-19c1-45bd-a632-dfa7a190f876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b11-Title']</value>
      <webElementGuid>0fb61ffd-8661-4492-817f-82b668ead514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b11-TitleWrapper']/div</value>
      <webElementGuid>9735d1d6-4e98-40c7-9f09-7576af6c6d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audit Trail'])[1]/following::div[4]</value>
      <webElementGuid>18381168-efe0-4f9b-88a0-c96e64ba097e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Logs'])[1]/following::div[4]</value>
      <webElementGuid>a4c807d5-a0dd-4706-95e1-157838835d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Utilities'])[2]/preceding::div[3]</value>
      <webElementGuid>642d1006-c416-41cb-95f8-d7f1e8ecffe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div</value>
      <webElementGuid>22ee97f7-61a0-418b-8d73-5f826730491d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b11-Title' and (text() = ' Utilities' or . = ' Utilities')]</value>
      <webElementGuid>b675be8d-a3d8-47d8-9597-12c4c19f6ee9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
