<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_CARD MRI Information Technology Inc_icon _9075e9</name>
   <tag></tag>
   <elementGuidId>0eae54a5-b240-4717-a732-c5bab5b13856</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-times.fa-1x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b11-Column2']/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9b702bd7-d70a-47e4-bfaa-8e45ffce484d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-times fa-1x</value>
      <webElementGuid>74e1dead-7db9-4dc6-8ece-8aa962f0bbb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b11-Column2&quot;)/div[1]/a[1]/i[@class=&quot;icon fa fa-times fa-1x&quot;]</value>
      <webElementGuid>dec88413-4c4b-4f24-a1ba-656376a1f70e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b11-Column2']/div/a/i</value>
      <webElementGuid>eb69dd86-3324-471b-9b2a-ec9920cf8642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/a/i</value>
      <webElementGuid>7927acf8-dd5f-4337-82bc-8452ac4db5f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
