<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Series Number_icon fa fa-th fa-2x</name>
   <tag></tag>
   <elementGuidId>1374a456-006a-43b0-97a5-9beec405abcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-th.fa-2x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-b2-$b1']/div/div/div[2]/div/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>56af6824-5f84-4249-801d-34735361b24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-th fa-2x</value>
      <webElementGuid>1acedca2-2f31-48bf-8506-692e27c8e909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-b2-$b1&quot;)/div[@class=&quot;user-info ThemeGrid_Margin10First&quot;]/div[@class=&quot;margin-left-s&quot;]/div[@class=&quot;popover custom-popover&quot;]/div[@class=&quot;popover-top&quot;]/div[@class=&quot;ThemeGrid_Margin3First&quot;]/div[1]/i[@class=&quot;icon fa fa-th fa-2x&quot;]</value>
      <webElementGuid>ad0d425f-443d-4576-8e1d-02ebd2c95ca2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-b2-$b1']/div/div/div[2]/div/div/div/i</value>
      <webElementGuid>a98e6212-fe33-4241-9c6f-b2dff507a5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div/div[2]/div/div/div/i</value>
      <webElementGuid>5e52b972-96b3-4460-b872-39eea0f7fa31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
