<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_---Select---AdministratorAuditorCash_5bdd56</name>
   <tag></tag>
   <elementGuidId>256067f1-52ba-4293-9dfc-a21ef1524086</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Dropdown1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dropdown1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fe5a8e60-827c-4625-9cca-2abef60fce3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>a1c5a4b7-5220-4d43-8d9c-f04528f0c792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>af9dceed-0c0a-4df6-b975-17673499e13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dropdown1</value>
      <webElementGuid>972619a4-6b39-49d4-8a08-e67b492c53be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select---AdministratorAuditorCashierExecutive DirectorExternal AuditorFinance AssistantFinance BookkeeperFinance ManagerFinance OfficerGeneral AccountantSr. Finance OfficerSupervisor</value>
      <webElementGuid>8eadf5ed-ad25-45a0-bd89-d15a83d484fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dropdown1&quot;)</value>
      <webElementGuid>09ef6bb7-9c24-4477-92a8-64cbccd20d4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dropdown1']</value>
      <webElementGuid>b859adfc-19d3-4f28-8e98-c2a3c690ea0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dropdown1-container']/select</value>
      <webElementGuid>6cabac9f-34e4-4c53-849e-2f4354fa2b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Possition:'])[1]/following::select[1]</value>
      <webElementGuid>d26767ee-1200-4669-a120-c75e49eb1afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/following::select[1]</value>
      <webElementGuid>8acbb9c9-8484-46a3-b13f-69d372c39ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate List'])[1]/preceding::select[1]</value>
      <webElementGuid>d204820b-6da9-4c98-aee6-ff6b247f8a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>097fc5f3-bb9f-4f4c-bced-56f630e316f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dropdown1' and (text() = '---Select---AdministratorAuditorCashierExecutive DirectorExternal AuditorFinance AssistantFinance BookkeeperFinance ManagerFinance OfficerGeneral AccountantSr. Finance OfficerSupervisor' or . = '---Select---AdministratorAuditorCashierExecutive DirectorExternal AuditorFinance AssistantFinance BookkeeperFinance ManagerFinance OfficerGeneral AccountantSr. Finance OfficerSupervisor')]</value>
      <webElementGuid>8ac31975-4a96-4d85-8c47-e2820eac4399</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
