<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Back to Manage Role Page</name>
   <tag></tag>
   <elementGuidId>123505ad-408a-4b38-964d-023067de4b13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-Background']/div/a[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>24901d98-719f-4cd0-ac6e-f0fd914d2ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back to Manage Role Page</value>
      <webElementGuid>5cc40dce-e3ac-4560-a9be-b0e5cd67db77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-Background&quot;)/div[1]/a[@class=&quot;ThemeGrid_MarginGutter&quot;]/span[1]</value>
      <webElementGuid>338b0bc7-1c22-4b25-b1ee-d2daa6481a2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-Background']/div/a[2]/span</value>
      <webElementGuid>f6679a36-36a3-47b4-8f9c-8e89158cafef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARD MRI Information Technology, INC.'])[1]/preceding::span[1]</value>
      <webElementGuid>339ba72a-30b1-4f4c-a9b4-6301c0e10fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Back to Manage Role Page']/parent::*</value>
      <webElementGuid>20f68f6b-3dc4-467e-b4a3-21f35023a9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>21900ff3-1e12-47c4-9a8c-dedb4e5091f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Back to Manage Role Page' or . = 'Back to Manage Role Page')]</value>
      <webElementGuid>ec2ed070-37ef-463f-b89a-c96f687d6230</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
