<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Generate List</name>
   <tag></tag>
   <elementGuidId>8fd4ab4b-5021-4ca2-bb80-54d384a937d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#View > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='View']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e8c4a47d-ce02-4c77-bc64-3a2321b5892b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate List </value>
      <webElementGuid>138246f6-c5d9-4cac-93fd-2fe253132100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;View&quot;)/span[1]</value>
      <webElementGuid>5662ae38-3caf-414d-b50c-13b564e35510</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='View']/span</value>
      <webElementGuid>a73eb419-ca26-4981-bdcf-bc0fb9a238ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Possition:'])[1]/following::span[2]</value>
      <webElementGuid>f08959f6-0585-4f7f-9515-49000f62d45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrator Role'])[1]/preceding::span[1]</value>
      <webElementGuid>f019ea9b-312a-433f-85ed-56ed16f0b2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GL Mapping'])[1]/preceding::span[2]</value>
      <webElementGuid>79dd60e9-5691-4d98-97d1-510d418bace3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generate List']/parent::*</value>
      <webElementGuid>fd5482da-4bd7-4576-a54c-c4e8f55bb08d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>ca0b7806-462b-4264-9f6f-419cde13a92e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Generate List ' or . = 'Generate List ')]</value>
      <webElementGuid>37f358a1-7728-4b7f-b3ea-b91f23a7532b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
